name: Publish Docker Image

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev"]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout 
        uses: actions/checkout@v4
      - name: Login to docker hub 
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: buildContainer 
        uses: docker/setup-buildx-action@v3 
      - name: build UI 
        uses: docker/build-push-action@v5
        with: 
            context: .
            file: ./apps/frontend/Dockerfile 
            push: true 
            tags: ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKERHUB_REPO}}:frontend
      - name: build backend
        uses: docker/build-push-action@v5
        with: 
            context: .
            file: ./apps/backend/Dockerfile 
            push: true 
            tags: ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKERHUB_REPO}}:backend
            
            
            
            
      
          
